repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest stable release of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.0
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8
        language: system

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.9.6
    hooks:
      - id: pylint
        args: [--disable=all, --enable=W, --enable=C]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        language: python
