repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest stable release of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
        stages: [commit, pre-push]
      - id: end-of-file-fixer
        stages: [commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--profile, black]
        stages: [commit, pre-push]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        stages: [commit, pre-push]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8
        language: system
        stages: [commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: [--disable=all, --enable=W, --enable=C]
        stages: [commit, pre-push]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        stages: [commit, pre-push]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        language: python
        stages: [commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        stages: [commit, pre-push]
