[tool.poetry]
name = "llama-lifecycle"
version = "0.1.0"
description = ""
authors = ["Achilleas Athanasiou Fragkoulis achilleasatha@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.5.3"
bumpver = "^2023.1129"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[bumpver]
current_version = "0.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
