name: Run pytest tests

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches:
#      - '*'

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pipx
      run: python3 -m pip install --user pipx

    - name: Add pipx to PATH
      run: export PATH="$HOME/.local/bin:$PATH"

    - name: Install Poetry using pipx
      run: pipx install poetry

    - name: Install project dependencies
      run: poetry install

    - name: Run pytest tests with coverage
      run: |
        poetry run pytest --cov=.

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
